name: Build and Publish

on:
  push:
    branches:
      - dotnet
    # tags:
    #   - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8'

      - name: Build
        run: |
          dotnet publish

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: wowa/bin/Release/net8.0/win-x64/publish/wowa.exe
