name: Build and Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Vlang
        run: |
          # Install dependencies needed for Vlang
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64

          # Download and install Vlang
          git clone https://github.com/vlang/v
          cd v
          make
          sudo ./v symlink

      - name: Build the project
        run: |
          v -os windows .

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: wowa.exe

